/**
 * Icon shim: keeps the old `svelte-feather-icons` component names (`ServerIcon`,
 * `XIcon`, …) but backs them with `lucide-svelte` (feather's maintained
 * successor, same stroke style). Lucide v1 renamed 7 feather-era names and
 * dropped their aliases, so those map to the new canonical icon below. Callers
 * only change their import source (from "svelte-feather-icons" to "$lib/icons").
 */
import {
  // Unchanged names (41).
  Archive,
  Book,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsDown,
  ChevronsUp,
  Clipboard,
  Code,
  Copy,
  CornerUpLeft,
  CornerUpRight,
  Download,
  File,
  FilePlus,
  FileText,
  Folder,
  FolderPlus,
  HardDrive,
  Image,
  Inbox,
  Info,
  Key,
  Link,
  Minus,
  Music,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Scissors,
  Search,
  Server,
  Settings,
  Terminal,
  Trash,
  Type,
  Upload,
  Video,
  X,
  Zap,
  // Renamed by lucide v1 (7).
  CircleCheck, // <- feather CheckCircle
  CircleQuestionMark, // <- feather HelpCircle
  CircleX, // <- feather XCircle
  CloudUpload, // <- feather UploadCloud
  LayoutGrid, // <- feather Grid
  Pen, // <- feather Edit
  TriangleAlert, // <- feather AlertTriangle
} from "lucide-svelte";

export {
  Archive as ArchiveIcon,
  Book as BookIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsDown as ChevronsDownIcon,
  ChevronsUp as ChevronsUpIcon,
  CircleCheck as CheckCircleIcon,
  CircleQuestionMark as HelpCircleIcon,
  CircleX as XCircleIcon,
  Clipboard as ClipboardIcon,
  CloudUpload as UploadCloudIcon,
  Code as CodeIcon,
  Copy as CopyIcon,
  CornerUpLeft as CornerUpLeftIcon,
  CornerUpRight as CornerUpRightIcon,
  Download as DownloadIcon,
  File as FileIcon,
  FilePlus as FilePlusIcon,
  FileText as FileTextIcon,
  Folder as FolderIcon,
  FolderPlus as FolderPlusIcon,
  HardDrive as HardDriveIcon,
  Image as ImageIcon,
  Inbox as InboxIcon,
  Info as InfoIcon,
  Key as KeyIcon,
  LayoutGrid as GridIcon,
  Link as LinkIcon,
  Minus as MinusIcon,
  Music as MusicIcon,
  Pen as EditIcon,
  Plus as PlusIcon,
  RefreshCw as RefreshCwIcon,
  RotateCcw as RotateCcwIcon,
  Save as SaveIcon,
  Scissors as ScissorsIcon,
  Search as SearchIcon,
  Server as ServerIcon,
  Settings as SettingsIcon,
  Terminal as TerminalIcon,
  Trash as TrashIcon,
  TriangleAlert as AlertTriangleIcon,
  Type as TypeIcon,
  Upload as UploadIcon,
  Video as VideoIcon,
  X as XIcon,
  Zap as ZapIcon,
};
