/**
 * Icon shim: keeps the old `svelte-feather-icons` component names (`ServerIcon`,
 * `XIcon`, …) but backs them with `@lucide/svelte` (feather's maintained
 * successor, same stroke style). Lucide v1 renamed 7 feather-era names and
 * dropped their aliases, so those map to the new canonical icon below. Callers
 * only change their import source (from "svelte-feather-icons" to "$lib/icons").
 *
 * `@lucide/svelte` is the renamed home of `lucide-svelte` (npm-deprecated at
 * 1.0.1); the icon names and props are unchanged, so this file is the only
 * place that needed the new specifier — and, because every other module imports
 * from here rather than the barrel, the only place that decides what gets
 * tree-shaken into the bundle.
 */
import {
  Archive,
  Book,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsDown,
  ChevronsUp,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clipboard,
  CloudUpload,
  Code,
  Copy,
  CornerUpLeft,
  CornerUpRight,
  Download,
  File,
  FilePlus,
  FileText,
  Folder,
  FolderPlus,
  HardDrive,
  Image,
  Inbox,
  Info,
  Key,
  LayoutGrid,
  Link,
  Minus,
  Music,
  Pen,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Scissors,
  Search,
  Server,
  Settings,
  Terminal,
  Trash,
  TriangleAlert,
  Type,
  Upload,
  Video,
  X,
  Zap,
} from "@lucide/svelte";

export {
  Archive as ArchiveIcon,
  Book as BookIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsDown as ChevronsDownIcon,
  ChevronsUp as ChevronsUpIcon,
  CircleCheck as CheckCircleIcon,
  CircleQuestionMark as HelpCircleIcon,
  CircleX as XCircleIcon,
  Clipboard as ClipboardIcon,
  CloudUpload as UploadCloudIcon,
  Code as CodeIcon,
  Copy as CopyIcon,
  CornerUpLeft as CornerUpLeftIcon,
  CornerUpRight as CornerUpRightIcon,
  Download as DownloadIcon,
  File as FileIcon,
  FilePlus as FilePlusIcon,
  FileText as FileTextIcon,
  Folder as FolderIcon,
  FolderPlus as FolderPlusIcon,
  HardDrive as HardDriveIcon,
  Image as ImageIcon,
  Inbox as InboxIcon,
  Info as InfoIcon,
  Key as KeyIcon,
  LayoutGrid as GridIcon,
  Link as LinkIcon,
  Minus as MinusIcon,
  Music as MusicIcon,
  Pen as EditIcon,
  Plus as PlusIcon,
  RefreshCw as RefreshCwIcon,
  RotateCcw as RotateCcwIcon,
  Save as SaveIcon,
  Scissors as ScissorsIcon,
  Search as SearchIcon,
  Server as ServerIcon,
  Settings as SettingsIcon,
  Terminal as TerminalIcon,
  Trash as TrashIcon,
  TriangleAlert as AlertTriangleIcon,
  Type as TypeIcon,
  Upload as UploadIcon,
  Video as VideoIcon,
  X as XIcon,
  Zap as ZapIcon,
};
